package GUI;

import TmdbApiMethods.MovieScraper;
import info.movito.themoviedbapi.model.MovieDb;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import javax.swing.ImageIcon;

public class AddWatchedPage extends javax.swing.JFrame {

    String movieNameAdd;
    String watchDateTemp;
    Boolean isWatched = true;

    MovieScraper scraperObj = new MovieScraper();

    ImageIcon doneIcon = new ImageIcon("src/main/resources/gui/AddWatchedDoneBT.png");
    ImageIcon star0ico = new ImageIcon("src/main/resources/gui/Additional/0star.png");
    ImageIcon star1ico = new ImageIcon("src/main/resources/gui/Additional/1star.png");
    ImageIcon star2ico = new ImageIcon("src/main/resources/gui/Additional/2star.png");
    ImageIcon star3ico = new ImageIcon("src/main/resources/gui/Additional/3star.png");
    ImageIcon star4ico = new ImageIcon("src/main/resources/gui/Additional/4star.png");
    ImageIcon star5ico = new ImageIcon("src/main/resources/gui/Additional/5star.png");

    int userRating = -1;

    public AddWatchedPage() {
        initComponents();

        staticStar.setVisible(false);
        movieList.setVisible(false);
        star.setVisible(false);
        dateTF.setVisible(false);

        movieTF.setOpaque(false);
        movieTF.setBackground(new java.awt.Color(255, 255, 255, 0));
        movieTF.setFont(new Font("Monsterrat", Font.PLAIN, 14));
        movieTF.setBorder(javax.swing.BorderFactory.createEmptyBorder());

        dateTF.setOpaque(false);
        dateTF.setBackground(new java.awt.Color(255, 255, 255, 0));
        dateTF.setBorder(javax.swing.BorderFactory.createEmptyBorder());

        //Placeholder
        dateTF.setText("01.01.2000");
        dateTF.setForeground(new Color(102, 102, 102));
        dateTF.setFont(new Font("Monsterrat", Font.ITALIC, 22));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movieList = new javax.swing.JComboBox<>();
        staticStar = new javax.swing.JLabel();
        star = new javax.swing.JLabel();
        dateTF = new javax.swing.JTextField();
        cancelBT = new javax.swing.JLabel();
        star1 = new javax.swing.JLabel();
        star2 = new javax.swing.JLabel();
        star3 = new javax.swing.JLabel();
        star4 = new javax.swing.JLabel();
        star5 = new javax.swing.JLabel();
        saveBT = new javax.swing.JLabel();
        doneBT = new javax.swing.JLabel();
        movieTF = new javax.swing.JTextField();
        page = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        movieList.setMaximumRowCount(10);
        getContentPane().add(movieList, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 210, -1));
        getContentPane().add(staticStar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 150, 25));
        getContentPane().add(star, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 150, 25));

        dateTF.setFont(new java.awt.Font("Montserrat", 1, 22)); // NOI18N
        dateTF.setForeground(new java.awt.Color(153, 153, 153));
        dateTF.setText("01.01.2001");
        dateTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateTFMouseClicked(evt);
            }
        });
        dateTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTFActionPerformed(evt);
            }
        });
        dateTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dateTFKeyTyped(evt);
            }
        });
        getContentPane().add(dateTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 150, -1));

        cancelBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBTMouseClicked(evt);
            }
        });
        getContentPane().add(cancelBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 500, 70, 20));

        star1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                star1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                star1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                star1MouseExited(evt);
            }
        });
        getContentPane().add(star1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 30, 50));

        star2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                star2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                star2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                star2MouseExited(evt);
            }
        });
        getContentPane().add(star2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 30, 50));

        star3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                star3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                star3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                star3MouseExited(evt);
            }
        });
        getContentPane().add(star3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 30, 50));

        star4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                star4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                star4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                star4MouseExited(evt);
            }
        });
        getContentPane().add(star4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 30, 50));

        star5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                star5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                star5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                star5MouseExited(evt);
            }
        });
        getContentPane().add(star5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 30, 50));

        saveBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveBTMouseClicked(evt);
            }
        });
        getContentPane().add(saveBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 100, 30));

        doneBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doneBTMouseClicked(evt);
            }
        });
        getContentPane().add(doneBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 60, 20));

        movieTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(movieTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 210, -1));

        page.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        page.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/AddWatchedPage.png"))); // NOI18N
        page.setOpaque(true);
        getContentPane().add(page, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBTMouseClicked
        this.dispose();
    }//GEN-LAST:event_cancelBTMouseClicked

    private void doneBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneBTMouseClicked
        movieList.removeAllItems();
        movieNameAdd = movieTF.getText();
        scraperObj.scrapeMovieList(movieNameAdd);
        star.setIcon(star0ico);

        int size = 6;

        if (size > scraperObj.getSearchResults().size()) {
            size = scraperObj.getSearchResults().size();
        }

        for (int i = 0; i < size; i++) {
            MovieDb currentMovie = scraperObj.getSearchResults().get(i);

            String relase = currentMovie.getReleaseDate();
            try {
                if (relase.isEmpty()) {
                    relase = "?";
                } else {
                    relase = relase.substring(0, 4);
                }
            } catch (NullPointerException e) {
                relase = "?";

            }

            movieList.addItem(currentMovie.getOriginalTitle()
                    + " (" + relase + ")");

        }

        movieTF.setText("");
        page.setIcon(doneIcon);
        movieList.setVisible(true);
        star.setVisible(true);
        dateTF.setVisible(true);

    }//GEN-LAST:event_doneBTMouseClicked

    private void star1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star1MouseEntered
        star.setIcon(star1ico);
    }//GEN-LAST:event_star1MouseEntered

    private void star1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star1MouseExited
        star.setIcon(star0ico);
    }//GEN-LAST:event_star1MouseExited

    private void star2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star2MouseEntered
        star.setIcon(star2ico);
    }//GEN-LAST:event_star2MouseEntered

    private void star2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star2MouseExited
        star.setIcon(star0ico);
    }//GEN-LAST:event_star2MouseExited

    private void star3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star3MouseEntered
        star.setIcon(star3ico);
    }//GEN-LAST:event_star3MouseEntered

    private void star3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star3MouseExited
        star.setIcon(star0ico);
    }//GEN-LAST:event_star3MouseExited

    private void star4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star4MouseEntered
        star.setIcon(star4ico);
    }//GEN-LAST:event_star4MouseEntered

    private void star4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star4MouseExited
        star.setIcon(star0ico);
    }//GEN-LAST:event_star4MouseExited

    private void star5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star5MouseEntered
        star.setIcon(star5ico);
    }//GEN-LAST:event_star5MouseEntered

    private void star5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star5MouseExited
        star.setIcon(star0ico);
    }//GEN-LAST:event_star5MouseExited


    private void star1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star1MouseClicked
        staticStar.setVisible(true);
        staticStar.setIcon(star1ico);
        star.setVisible(false);
        userRating = 1;
    }//GEN-LAST:event_star1MouseClicked

    private void star2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star2MouseClicked
        staticStar.setVisible(true);
        staticStar.setIcon(star2ico);
        star.setVisible(false);
        userRating = 2;
    }//GEN-LAST:event_star2MouseClicked

    private void star3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star3MouseClicked
        staticStar.setVisible(true);
        staticStar.setIcon(star3ico);
        star.setVisible(false);
        userRating = 3;
    }//GEN-LAST:event_star3MouseClicked

    private void star4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star4MouseClicked
        staticStar.setVisible(true);
        staticStar.setIcon(star4ico);
        star.setVisible(false);
        userRating = 4;
    }//GEN-LAST:event_star4MouseClicked

    private void star5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star5MouseClicked
        staticStar.setVisible(true);
        staticStar.setIcon(star5ico);
        star.setVisible(false);
        userRating = 5;
    }//GEN-LAST:event_star5MouseClicked

    private void dateTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTFActionPerformed

    private void dateTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateTFMouseClicked
        if (dateTF.getText().equals("01.01.2000")) {
            dateTF.setText("");
            dateTF.setForeground(Color.BLACK);
            dateTF.setFont(new Font("Monsterrat", Font.PLAIN, 22));
        }
    }//GEN-LAST:event_dateTFMouseClicked

    private void dateTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateTFKeyTyped
        if (dateTF.getText().equals("01.01.2000")) {
            dateTF.setText("");
            dateTF.setForeground(Color.BLACK);
            dateTF.setFont(new Font("Monsterrat", Font.PLAIN, 22));
        }
    }//GEN-LAST:event_dateTFKeyTyped

    private void saveBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBTMouseClicked
        if (saveBT.isVisible()) {
            watchDateTemp = dateTF.getText(); //03.02.2016 ise
            String watchDateString = null;

            if (!watchDateTemp.equals("01.01.2000")) {
                String watchDay = watchDateTemp.substring(0, 2); //03
                String watchMonth = watchDateTemp.substring(3, 5); //02
                String watchYear = watchDateTemp.substring(6, 10); //2016
                watchDateString = "" + watchYear + "-" + watchMonth + "-" + watchDay;
            }

            int index = movieList.getSelectedIndex();
            scraperObj.decideMovieIndex(index);

            try {
                scraperObj.createMovieObject(isWatched, watchDateString, userRating);
            } catch (SQLException ex) {
                ex.printStackTrace();
            }

            Page3.setPosters();

            System.out.println("SAVE BUTONUNA BASILDI, DEVAMI IMPLEMENT EDILMELI");
            //BURADAN MOVIE INFO AÇILABİLİR VEYA YENİ BİR FİLM EKLENMESİ İÇİN HER ŞEY BOŞALABİLİR

        }

    }//GEN-LAST:event_saveBTMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddWatchedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddWatchedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddWatchedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddWatchedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddWatchedPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancelBT;
    private javax.swing.JTextField dateTF;
    private javax.swing.JLabel doneBT;
    private javax.swing.JComboBox<String> movieList;
    private javax.swing.JTextField movieTF;
    private javax.swing.JLabel page;
    private javax.swing.JLabel saveBT;
    private javax.swing.JLabel star;
    private javax.swing.JLabel star1;
    private javax.swing.JLabel star2;
    private javax.swing.JLabel star3;
    private javax.swing.JLabel star4;
    private javax.swing.JLabel star5;
    private javax.swing.JLabel staticStar;
    // End of variables declaration//GEN-END:variables
}
