package GUI;

import Journal.Movie;
import MYSQLMethods.MovieDatabaseManager;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import org.imgscalr.Scalr;

import System.SystemClass;

public class MovieInfoPage extends javax.swing.JFrame {
    
    public MovieInfoPage() {
        initComponents();
        
        page.setIcon(new ImageIcon("src/main/resources/gui/9.png"));
        
        String starPath = null;
        switch (SystemClass.currentMovie.userRating) {
            case -1:
                starPath = "src/main/resources/gui/Additional/0star.png";
                break;
            
            case 1:
                starPath = "src/main/resources/gui/Additional/1star.png";
                break;            
            
            case 2:
                starPath = "src/main/resources/gui/Additional/2star.png";
                break;
            
            case 3:
                starPath = "src/main/resources/gui/Additional/3star.png";
                break;
            
            case 4:
                starPath = "src/main/resources/gui/Additional/4star.png";
                break;            
            
            case 5:
                starPath = "src/main/resources/gui/Additional/5star.png";
                break;            
            
            default:
                throw new AssertionError();
        }
        
        ImageIcon starIcon = new ImageIcon(starPath);
        
        String currentPoster = "src/main/resources/posters/" + SystemClass.currentMovie.name + "w250.jpg";
        ImageIcon posterIcon = new ImageIcon(currentPoster);
        
        poster.setIcon(posterIcon);
        star.setIcon(starIcon);
        
        title.setText(SystemClass.currentMovie.name);
        relaseYear.setText(SystemClass.currentMovie.relaseDate);
        genre.setText(SystemClass.currentMovie.genreList.toString().substring(1, SystemClass.currentMovie.genreList.toString().length() - 1));
        watchDate.setText(SystemClass.currentMovie.watchDate);
        

        
        String firstCrew = "";
        String secondCrew = "";
        String thirdCrew = "";
        
        String firstCast = "";
        String secondCast = "";
        String thirdCast = "";
        
        try {
             firstCast = SystemClass.currentMovie.castList.get(0);
             secondCast = SystemClass.currentMovie.castList.get(1);
             thirdCast = SystemClass.currentMovie.castList.get(2);
            
            firstCrew =SystemClass.currentMovie.crewList.get(0);
            secondCrew =  SystemClass.currentMovie.crewList.get(1);
            thirdCrew = SystemClass.currentMovie.crewList.get(2);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        castLabel.setText(firstCast);
        castLabel2.setText(secondCast);
        castLabel3.setText(thirdCast);
        crewLabel.setText(firstCrew);
        crewLabel2.setText(secondCrew);
        crewLabel3.setText(thirdCrew);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        watchDate = new javax.swing.JLabel();
        star = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        genre = new javax.swing.JLabel();
        castLabel = new javax.swing.JLabel();
        castLabel2 = new javax.swing.JLabel();
        castLabel3 = new javax.swing.JLabel();
        crewLabel = new javax.swing.JLabel();
        crewLabel2 = new javax.swing.JLabel();
        crewLabel3 = new javax.swing.JLabel();
        relaseYear = new javax.swing.JLabel();
        poster = new javax.swing.JLabel();
        cancelBT = new javax.swing.JLabel();
        page = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        watchDate.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        getContentPane().add(watchDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 210, 20));
        getContentPane().add(star, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 150, 25));

        title.setFont(new java.awt.Font("Montserrat Medium", 0, 24)); // NOI18N
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 500, 30));

        genre.setFont(new java.awt.Font("Montserrat Medium", 0, 24)); // NOI18N
        getContentPane().add(genre, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 440, 30));

        castLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 24)); // NOI18N
        getContentPane().add(castLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 530, 30));

        castLabel2.setFont(new java.awt.Font("Montserrat Medium", 0, 24)); // NOI18N
        getContentPane().add(castLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 530, 30));

        castLabel3.setFont(new java.awt.Font("Montserrat Medium", 0, 24)); // NOI18N
        getContentPane().add(castLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 530, 30));

        crewLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 24)); // NOI18N
        getContentPane().add(crewLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 470, 30));

        crewLabel2.setFont(new java.awt.Font("Montserrat Medium", 0, 24)); // NOI18N
        getContentPane().add(crewLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 470, 30));

        crewLabel3.setFont(new java.awt.Font("Montserrat Medium", 0, 24)); // NOI18N
        getContentPane().add(crewLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 460, 30));

        relaseYear.setFont(new java.awt.Font("Montserrat Medium", 0, 24)); // NOI18N
        getContentPane().add(relaseYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 130, 30));
        getContentPane().add(poster, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 250, 375));

        cancelBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBTMouseClicked(evt);
            }
        });
        getContentPane().add(cancelBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 500, 90, 40));

        page.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        page.setOpaque(true);
        getContentPane().add(page, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBTMouseClicked
        this.dispose();
    }//GEN-LAST:event_cancelBTMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieInfoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieInfoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieInfoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieInfoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieInfoPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancelBT;
    private javax.swing.JLabel castLabel;
    private javax.swing.JLabel castLabel2;
    private javax.swing.JLabel castLabel3;
    private javax.swing.JLabel crewLabel;
    private javax.swing.JLabel crewLabel2;
    private javax.swing.JLabel crewLabel3;
    private javax.swing.JLabel genre;
    private javax.swing.JLabel page;
    private javax.swing.JLabel poster;
    private javax.swing.JLabel relaseYear;
    private javax.swing.JLabel star;
    private javax.swing.JLabel title;
    private javax.swing.JLabel watchDate;
    // End of variables declaration//GEN-END:variables
}
