package GUI;

import LoginSignUp.*;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

public class Page1 extends javax.swing.JFrame {

    public Page1() {
        initComponents();
        clickheretologin.setText("Already registered? Click here to login.");

        nameTextField.setOpaque(false);
        nameTextField.setBackground(new java.awt.Color(255, 255, 255, 0));
        nameTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder());

        usernameTextField.setOpaque(false);
        usernameTextField.setBackground(new java.awt.Color(255, 255, 255, 0));
        usernameTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder());

        passwordField.setOpaque(false);
        passwordField.setBackground(new java.awt.Color(255, 255, 255, 0));
        passwordField.setBorder(javax.swing.BorderFactory.createEmptyBorder());

        //Placeholder
        nameTextField.setText("Name");
        nameTextField.setForeground(new Color(102, 102, 102));
        nameTextField.setFont(new Font("Monsterrat", Font.ITALIC, 14));

        usernameTextField.setText("Username");
        usernameTextField.setForeground(new Color(102, 102, 102));
        usernameTextField.setFont(new Font("Monsterrat", Font.ITALIC, 14));

        passwordField.setText("Password");
        passwordField.setForeground(new Color(102, 102, 102));
        passwordField.setFont(new Font("Monsterrat", Font.ITALIC, 14));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameTextField = new javax.swing.JTextField();
        usernameTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        exitEnterBT = new javax.swing.JLabel();
        clickheretologin = new javax.swing.JLabel();
        signupBT = new javax.swing.JLabel();
        page = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameTextFieldMouseClicked(evt);
            }
        });
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        nameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameTextFieldKeyTyped(evt);
            }
        });
        getContentPane().add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 210, -1));

        usernameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameTextFieldMouseClicked(evt);
            }
        });
        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });
        usernameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameTextFieldKeyTyped(evt);
            }
        });
        getContentPane().add(usernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 210, -1));

        passwordField.setText("jPasswordField1");
        passwordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordFieldMouseClicked(evt);
            }
        });
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
        });
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 210, -1));

        exitEnterBT.setToolTipText("");
        exitEnterBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitEnterBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitEnterBTMouseClicked(evt);
            }
        });
        getContentPane().add(exitEnterBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 30, 30));

        clickheretologin.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        clickheretologin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clickheretologin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickheretologinMouseClicked(evt);
            }
        });
        getContentPane().add(clickheretologin, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, 260, 20));

        signupBT.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        signupBT.setForeground(new java.awt.Color(255, 255, 255));
        signupBT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signupBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signupBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupBTMouseClicked(evt);
            }
        });
        getContentPane().add(signupBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 390, 90, 30));

        page.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        page.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/1.png"))); // NOI18N
        page.setFocusable(false);
        page.setOpaque(true);
        getContentPane().add(page, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitEnterBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitEnterBTMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitEnterBTMouseClicked

    private void clickheretologinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickheretologinMouseClicked
        Page2 page2 = new Page2();
        page2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_clickheretologinMouseClicked

    private void signupBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupBTMouseClicked
        String name = nameTextField.getText();
        String username = usernameTextField.getText();
        String password = String.valueOf(passwordField.getPassword());

        boolean isSigned = false;

        try {
            isSigned = SignUp.addUser(name, "tempSurname", username, password);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        if (isSigned) {
            clickheretologin.setForeground(new Color(99, 5, 153));
            clickheretologin.setFont(new Font("Montserrat Medium", Font.BOLD, 12));
            clickheretologin.setText("Register success, click here to login!");

        } else if (!isSigned) {
            clickheretologin.setForeground(new Color(204, 0, 51));
            clickheretologin.setFont(new Font("Montserrat Medium", Font.BOLD, 12));
            clickheretologin.setText("Already registered! Click here to login!");

        }

        //otomatik olarak login(); çalıştır
        //bu ekranı dispose'la, mainFrame'i new'le
    }//GEN-LAST:event_signupBTMouseClicked

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed

    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed

    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void nameTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameTextFieldMouseClicked
        if (nameTextField.getText().equals("Name")) {
            nameTextField.setText("");
            nameTextField.setForeground(Color.BLACK);
            nameTextField.setFont(new Font("Monsterrat", Font.PLAIN, 14));
        }
    }//GEN-LAST:event_nameTextFieldMouseClicked

    private void nameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextFieldKeyTyped
        if (nameTextField.getText().equals("Name")) {
            nameTextField.setText("");
            nameTextField.setForeground(Color.BLACK);
            nameTextField.setFont(new Font("Monsterrat", Font.PLAIN, 14));
        }
    }//GEN-LAST:event_nameTextFieldKeyTyped

    private void usernameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameTextFieldKeyTyped
        if (usernameTextField.getText().equals("Username")) {
            usernameTextField.setText("");
            usernameTextField.setForeground(Color.BLACK);
            usernameTextField.setFont(new Font("Monsterrat", Font.PLAIN, 14));
        }
    }//GEN-LAST:event_usernameTextFieldKeyTyped

    private void usernameTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameTextFieldMouseClicked
        if (usernameTextField.getText().equals("Username")) {
            usernameTextField.setText("");
            usernameTextField.setForeground(Color.BLACK);
            usernameTextField.setFont(new Font("Monsterrat", Font.PLAIN, 14));
        }
    }//GEN-LAST:event_usernameTextFieldMouseClicked

    private void passwordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordFieldMouseClicked
        if (String.valueOf(passwordField.getPassword()).equals("Password")) {
            passwordField.setText("");
            passwordField.setForeground(Color.BLACK);
            passwordField.setFont(new Font("Monsterrat", Font.PLAIN, 14));
        }
    }//GEN-LAST:event_passwordFieldMouseClicked

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed
        if (String.valueOf(passwordField.getPassword()).equals("Password")) {
            passwordField.setText("");
            passwordField.setForeground(Color.BLACK);
            passwordField.setFont(new Font("Monsterrat", Font.PLAIN, 14));
        }
    }//GEN-LAST:event_passwordFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clickheretologin;
    private javax.swing.JLabel exitEnterBT;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel page;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel signupBT;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
