package GUI;

import MYSQLMethods.MovieDatabaseManager;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class ShowWatchedPage extends javax.swing.JFrame {

    public ShowWatchedPage() {
        initComponents();

        DefaultTableModel watchedModel = (DefaultTableModel) watchedTable.getModel();

        watchedModel.setRowCount(0);

        MovieDatabaseManager movieDatabaseManager = null;
        try {
            movieDatabaseManager = new MovieDatabaseManager();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        ArrayList<Object[]> movieList = null;

        try {
            movieList = movieDatabaseManager.getWatchedMoviesData();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        for (int i = 0; i < movieList.size(); i++) {
            watchedModel.addRow(movieList.get(i));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        watchedTable = new javax.swing.JTable();
        cancelBT = new javax.swing.JLabel();
        page = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        watchedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Movie Name", "Watch Date", "Rating"
            }
        ));
        jScrollPane1.setViewportView(watchedTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 890, -1));

        cancelBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBTMouseClicked(evt);
            }
        });
        getContentPane().add(cancelBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 490, 90, 40));

        page.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        page.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/blank.png"))); // NOI18N
        page.setOpaque(true);
        getContentPane().add(page, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBTMouseClicked
        this.dispose();
    }//GEN-LAST:event_cancelBTMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowWatchedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowWatchedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowWatchedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowWatchedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowWatchedPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancelBT;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel page;
    private javax.swing.JTable watchedTable;
    // End of variables declaration//GEN-END:variables
}
